### ISSUE TITLE
about pool_method

### ISSUE THREAD

**Issue by kimjisoo12** [microsoft/Focal-Transformer#12]
Hi,I want to know doing sub-windows pooling，If I want to follow the sub-window-pooling method introduced in the paper, which pooling method should I select.

thank you  very much

![8556cddfd39537c3339c6b7f5f3a757](https://user-images.githubusercontent.com/89247664/142718750-5f9191dc-5ad2-45fe-9535-7184f0dcfe11.png)

**Comment by jwyang** [comment]
Hi, the default is "fc" pooling as described in our paper.
