### ISSUE TITLE
how can i extract features ?

### ISSUE THREAD

**Issue by mathshangw** [microsoft/Focal-Transformer#15]
Thanks for sharing the code ! i need to extract the feature for the images before classifying it .. i mean ignoring the layer of classification .. so i tried this code but i think it is wrong 
```
class Identity(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x

PATH = 'focal-base-is224-ws7.pth'
model = FocalTransformer()
model.load_state_dict(torch.load(PATH),strict=False)
model.head = Identity()
```

**Comment by SamMohel** [comment]
I have the same question please can someone help?
