### ISSUE TITLE
Focal Transformer on 1-D Data

### ISSUE THREAD

**Issue by sauradip** [microsoft/Focal-Transformer#4]
Great Work !

My query is that : can this method be run on 1-D features ? Because the pooling operations done before flattening is done for 2-D representation !

**Comment by jwyang** [comment]
Hi, 

thanks! Yes, you can simply split the 1-D into multiple window chunks and then perform pooling for each window by directly applying a fc layer without any further flatten as I did for 2d windows.

thanks,
